// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvoflukhsrxtifziqyiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2b2ZsdWtoc3J4dGlmemlxeWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTE4MDQsImV4cCI6MjA3Mzg4NzgwNH0.5teqO31n1FlYzpWc0NEwQQzR8TX9vJrpWkiOj7ZMwyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});